spiped_connections: []
caddy_features: http.prometheus
caddy_setcap: yes
caddy_systemd_capabilities_enabled: True
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_config: |
  monitor.noisetor.net {
    gzip
    prometheus
    tls p@trickod.com
    log /var/log/caddy/access.log

    proxy / localhost:3000 {
      transparent
    }
  }

  alertmanager.noisetor.net {
    gzip
    prometheus
    tls p@trickod.com
    log /var/log/caddy/access.log

    proxy / localhost:9117 {
      transparent
    }
  }
