---
- name: install spiped
  apt:
    package: spiped
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - debian

- name: install spiped systemd unit
  copy:
    src: etc/systemd/system/spiped.service
    dest: /etc/systemd/system/spiped.service
  tags:
    - debian
  when: spiped_connections|length == 0

- name: ensure spiped directory exists
  file:
    dest: /etc/spiped
    owner: root
    group: root
    state: directory
  tags:
    - debian

- name: copy the noisetor keyfile
  copy:
    src: etc/spiped/noisetor.key
    dest: /etc/spiped/noisetor.key
    owner: root
    group: root
    mode: 0600
  tags:
    - debian

- name: enable the systemd spiped client receiving service
  service:
    name: spiped
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - debian
  when: spiped_connections|length == 0

- name: install systemd client unit files
  with_items: "{{ spiped_connections }}"
  template:
    src: etc/systemd/system/spiped-client.service
    dest: "/etc/systemd/system/spiped-client-{{ item.name }}.service"
    owner: root
    group: root
  tags:
    - debian

- name: start/enable the outbound spiped clients
  with_items: "{{ spiped_connections }}"
  systemd:
    name: "spiped-client-{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - debian
