---
- name: Install grafana key
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present

- name: ensure apt-transport-https is installed
  apt:
    package: apt-transport-https
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Install grafana repo
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ {{ ansible_distribution_release }} main"
    state: present

- name: Install grafana package
  apt: pkg={{ item }} state=latest install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - grafana

- name: Configure grafana
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini

- name: Start grafana
  systemd: name=grafana-server enabled=yes state=started daemon_reload=yes
