- hosts: all
  tags: [node_exporter]
  roles:
    - node_exporter

- hosts: prometheus
  tags: [prometheus]
  roles:
    - blackbox_exporter
    - prometheus
    - snmp_exporter

- hosts: grafana
  tags: [grafana]
  roles:
    - node_exporter
    #- antoiner77.caddy
    - grafana
