- hosts: prometheus
  remote_user: root
  tags: [prometheus]
  roles:
    - antoiner77.caddy
    - blackbox_exporter
    - grafana
    - node_exporter
    - prometheus
    - snmp_exporter

- hosts: node_exporter
  tags: [node_exporter]
  roles:
    - node_exporter
