- hosts: prometheus
  tags: [prometheus]
  roles:
    - hardening
    - buster
    - golang
    - antoiner77.caddy
    - blackbox_exporter
    - grafana
    - node_exporter
    - prometheus
    - snmp_exporter
    - alertmanager
    - spiped
  vars:
    spiped_connections:
      - name: exit-01
        port: 9101
        dest: exit-01a.noisetor.net
      - name: exit-03
        port: 9102
        dest: exit-03a.noisetor.net
      - name: bridge-01
        port: 9103
        dest: bridge-01.noisetor.net

- hosts: node_exporter
  tags: [node_exporter]
  roles:
    - node_exporter
    - spiped
  vars:
    spiped_connections: []

- hosts: grafana
  tags: [grafana]
  roles:
    - antoiner77.caddy
    - grafana
