go_arch: amd64

node_exporter_install_path: /srv/node_exporter
node_exporter_textfiles_path: /srv/node_exporter/textfiles
node_exporter_collectors_enable: []
node_exporter_collectors_disable: []
node_exporter_version: 0.15.2
node_exporter_listen_address: "localhost:9100"
node_exporter_path: "{{ node_exporter_install_path }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}"
