- name: ensure .ssh directory exists
  file:
    dest: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: install SSH keys
  copy:
    src: authorized_keys
    dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
