- name: Creating snmp_exporter dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ snmp_exporter_install_path }}"

- name: untar snmp_exporter tarball
  unarchive:
    src: "{{ snmp_exporter_tarball_url }}"
    dest: "{{ snmp_exporter_install_path }}"
    mode: 0755
    copy: no

- name: Install config file
  copy:
    src: snmp.yml
    dest: "{{ snmp_exporter_install_path }}/snmp.yml"
  notify:
  - restart snmp_exporter

- name: Install snmp_exporter systemd service file
  notify:
  - restart snmp_exporter
  template:
    src: snmp_exporter.service
    dest: /etc/systemd/system/snmp_exporter.service

- name: Enable and start snmp_exporter service
  systemd:
    name: snmp_exporter.service
    state: started
    enabled: yes
    daemon_reload: yes
