---

- name: install golang and git (FreeBSD)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - go
    - git
  when: ansible_system == "FreeBSD"
  tags:
    - freebsd

- name: install FreeBSD configuration file
  when: ansible_system == "FreeBSD"
  copy:
    src: /usr/local/etc/rc.d/node_exporter
    dest: /usr/local/etc/rc.d/node_exporter
    mode: 0555
  tags:
    - freebsd

- name: enable node_exporter service
  service:
    name: node_exporter
    enabled: yes
    state: started
  tags:
    - freebsd
