- name: Creating node_exporter dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: nobody
    group: nogroup
  with_items:
    - "{{ node_exporter_textfiles_path }}"

- name: make GOPATH directory
  file:
    dest: /opt/go
    state: directory

- name: execute Debian installation
  include: debian.yml
  when: ansible_distribution == "Debian"

- name: execute FreeBSD installation
  include: freebsd.yml
  when: ansible_distribution == "FreeBSD"

- name: clone node_exporter source code
  git:
    repo: https://github.com/prometheus/node_exporter.git
    dest: /opt/go/src/github.com/prometheus/node_exporter
    depth: 1

- name: build and install go
  environment:
    GOPATH: /opt/go
  command: go install github.com/prometheus/node_exporter
  args:
    creates: /opt/go/bin/node_exporter
