go_arch: amd64

prometheus_user:   prometheus
prometheus_group:  prometheus

prometheus_install_path:         /srv/prometheus
prometheus_config_path:          /srv/prometheus/config
prometheus_db_path:              /srv/prometheus/data
prometheus_rule_path:            "{{ prometheus_config_path }}/rules"
prometheus_file_sd_config_path:  "{{ prometheus_config_path }}/targets"

prometheus_listen_address: "localhost:9090"

prometheus_version: 1.8.1
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download

prometheus_tarball_url: "{{ prometheus_download_url }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
prometheus_path: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}"

prometheus_storage_tsdb_retention: "365d"

prometheus_config:
  global:
    scrape_interval: "15s"
    evaluation_interval: "15s"
    scrape_timeout: "10s"
  rule_files:
  - 'rules/*.rules'
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'alertmanager'
      static_configs:
        - targets: ["{{ alertmanager_listen_address }}"]
    - job_name: blackbox_ssh
      metrics_path: "/probe"
      params:
        module: [ssh_banner]
      static_configs:
        - targets:
            - exit-01a.noisetor.net:22
            - exit-03a.noisetor.net:22
            - bridge-01.noisetor.net:22
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement:  "{{ blackbox_exporter_listen_address }}"
    - job_name: blackbox_http
      metrics_path: "/probe"
      params:
        module: [http_2xx]
      static_configs:
        - targets:
            - http://exit-01a.noisetor.net
            - http://exit-01b.noisetor.net
            - http://exit-01c.noisetor.net
            - http://exit-01d.noisetor.net
            - http://exit-03a.noisetor.net
            - http://exit-03b.noisetor.net
            - http://exit-03c.noisetor.net
            - http://exit-03d.noisetor.net
            - https://noisebridge.net
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement:  "{{ blackbox_exporter_listen_address }}"
    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
      - targets:
        - localhost:9100
        - localhost:9101
        - localhost:9102
        - localhost:9103
